// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: label.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addProjectLabels = `-- name: AddProjectLabels :exec
INSERT INTO project_label (project_id, label_id) 
SELECT $1,unnest($2::uuid[])
`

type AddProjectLabelsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	LabelIds  []uuid.UUID `json:"label_ids"`
}

func (q *Queries) AddProjectLabels(ctx context.Context, arg AddProjectLabelsParams) error {
	_, err := q.db.Exec(ctx, addProjectLabels, arg.ProjectID, arg.LabelIds)
	return err
}

const addTaskLabels = `-- name: AddTaskLabels :exec
INSERT INTO task_label (task_id, label_id) 
SELECT $1,unnest($2::uuid[])
`

type AddTaskLabelsParams struct {
	TaskID   uuid.UUID   `json:"task_id"`
	LabelIds []uuid.UUID `json:"label_ids"`
}

func (q *Queries) AddTaskLabels(ctx context.Context, arg AddTaskLabelsParams) error {
	_, err := q.db.Exec(ctx, addTaskLabels, arg.TaskID, arg.LabelIds)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO label (id,workspace_id, scope, name, color,created_at,updated_at)
 VALUES (gen_random_uuid(),$1, $2, $3, $4,NOW(),NOW())
RETURNING id, workspace_id, scope, name, color, created_at, updated_at
`

type CreateLabelParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Scope       LabelScope `json:"scope"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.WorkspaceID,
		arg.Scope,
		arg.Name,
		arg.Color,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Scope,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM label WHERE id = $1 AND workspace_id = $2
`

type DeleteLabelParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) error {
	_, err := q.db.Exec(ctx, deleteLabel, arg.ID, arg.WorkspaceID)
	return err
}

const deleteProjectLabels = `-- name: DeleteProjectLabels :exec
DELETE FROM project_label WHERE project_id = $1
`

func (q *Queries) DeleteProjectLabels(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectLabels, projectID)
	return err
}

const deleteTaskLabels = `-- name: DeleteTaskLabels :exec
DELETE FROM task_label WHERE task_id = $1
`

func (q *Queries) DeleteTaskLabels(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskLabels, taskID)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT id, workspace_id, scope, name, color, created_at, updated_at FROM label WHERE id = $1 AND workspace_id = $2
`

type GetLabelParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetLabel(ctx context.Context, arg GetLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, getLabel, arg.ID, arg.WorkspaceID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Scope,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabelScopesByIds = `-- name: ListLabelScopesByIds :many
SELECT id, scope FROM label WHERE workspace_id = $1
AND id = ANY($2::uuid[])
`

type ListLabelScopesByIdsParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Ids         []uuid.UUID `json:"ids"`
}

type ListLabelScopesByIdsRow struct {
	ID    uuid.UUID  `json:"id"`
	Scope LabelScope `json:"scope"`
}

// 打标校验用：只取 id 与 scope，命中行数不足 = 有 id 不属于本工作区；行数齐但 scope 不符 = scope 不匹配
func (q *Queries) ListLabelScopesByIds(ctx context.Context, arg ListLabelScopesByIdsParams) ([]ListLabelScopesByIdsRow, error) {
	rows, err := q.db.Query(ctx, listLabelScopesByIds, arg.WorkspaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelScopesByIdsRow
	for rows.Next() {
		var i ListLabelScopesByIdsRow
		if err := rows.Scan(&i.ID, &i.Scope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByWorkspace = `-- name: ListLabelsByWorkspace :many
SELECT id, workspace_id, scope, name, color, created_at, updated_at FROM label WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListLabelsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabelsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Scope,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByWorkspaceAndScope = `-- name: ListLabelsByWorkspaceAndScope :many
SELECT id, workspace_id, scope, name, color, created_at, updated_at FROM label WHERE workspace_id = $1 AND scope = $2
ORDER BY created_at
`

type ListLabelsByWorkspaceAndScopeParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Scope       LabelScope `json:"scope"`
}

func (q *Queries) ListLabelsByWorkspaceAndScope(ctx context.Context, arg ListLabelsByWorkspaceAndScopeParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabelsByWorkspaceAndScope, arg.WorkspaceID, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Scope,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE label SET name = $1, color = $2, updated_at = NOW()
WHERE id = $3 AND workspace_id = $4
RETURNING id, workspace_id, scope, name, color, created_at, updated_at
`

type UpdateLabelParams struct {
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Scope,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
