// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO member (id,workspace_id,name,email,avatar_color,created_at,updated_at)
VALUES(
    gen_random_uuid(),$1,$2,$3,$4,NOW(),NOW()
)
RETURNING id, workspace_id, name, email, avatar_color, user_id, created_at, updated_at
`

type CreateMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Email       *string   `json:"email"`
	AvatarColor string    `json:"avatar_color"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.WorkspaceID,
		arg.Name,
		arg.Email,
		arg.AvatarColor,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.AvatarColor,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM member WHERE id = $1 AND workspace_id = $2
`

type DeleteMemberParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.ID, arg.WorkspaceID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, workspace_id, name, email, avatar_color, user_id, created_at, updated_at FROM member WHERE id = $1 AND workspace_id = $2
`

type GetMemberParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, arg.ID, arg.WorkspaceID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.AvatarColor,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersByWorkspace = `-- name: ListMembersByWorkspace :many
SELECT id, workspace_id, name, email, avatar_color, user_id, created_at, updated_at FROM member WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListMembersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Email,
			&i.AvatarColor,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE member SET name = $1, email = $2, avatar_color = $3, updated_at=NOW()
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, name, email, avatar_color, user_id, created_at, updated_at
`

type UpdateMemberParams struct {
	Name        string    `json:"name"`
	Email       *string   `json:"email"`
	AvatarColor string    `json:"avatar_color"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.Name,
		arg.Email,
		arg.AvatarColor,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Email,
		&i.AvatarColor,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
