// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"cloud.google.com/go/civil"
	"github.com/google/uuid"
)

type LabelScope string

const (
	LabelScopeTask    LabelScope = "task"
	LabelScopeProject LabelScope = "project"
)

func (e *LabelScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LabelScope(s)
	case string:
		*e = LabelScope(s)
	default:
		return fmt.Errorf("unsupported scan type for LabelScope: %T", src)
	}
	return nil
}

type NullLabelScope struct {
	LabelScope LabelScope `json:"label_scope"`
	Valid      bool       `json:"valid"` // Valid is true if LabelScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLabelScope) Scan(value interface{}) error {
	if value == nil {
		ns.LabelScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LabelScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLabelScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LabelScope), nil
}

func (e LabelScope) Valid() bool {
	switch e {
	case LabelScopeTask,
		LabelScopeProject:
		return true
	}
	return false
}

func AllLabelScopeValues() []LabelScope {
	return []LabelScope{
		LabelScopeTask,
		LabelScopeProject,
	}
}

type ProjectStatus string

const (
	ProjectStatusBacklog    ProjectStatus = "backlog"
	ProjectStatusPlanned    ProjectStatus = "planned"
	ProjectStatusInProgress ProjectStatus = "in_progress"
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusCanceled   ProjectStatus = "canceled"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus `json:"project_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusBacklog,
		ProjectStatusPlanned,
		ProjectStatusInProgress,
		ProjectStatusCompleted,
		ProjectStatusCanceled:
		return true
	}
	return false
}

func AllProjectStatusValues() []ProjectStatus {
	return []ProjectStatus{
		ProjectStatusBacklog,
		ProjectStatusPlanned,
		ProjectStatusInProgress,
		ProjectStatusCompleted,
		ProjectStatusCanceled,
	}
}

type TaskStatus string

const (
	TaskStatusBacklog    TaskStatus = "backlog"
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusCanceled   TaskStatus = "canceled"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusBacklog,
		TaskStatusTodo,
		TaskStatusInProgress,
		TaskStatusDone,
		TaskStatusCanceled:
		return true
	}
	return false
}

func AllTaskStatusValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusBacklog,
		TaskStatusTodo,
		TaskStatusInProgress,
		TaskStatusDone,
		TaskStatusCanceled,
	}
}

type ViewEntity string

const (
	ViewEntityTask    ViewEntity = "task"
	ViewEntityProject ViewEntity = "project"
)

func (e *ViewEntity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ViewEntity(s)
	case string:
		*e = ViewEntity(s)
	default:
		return fmt.Errorf("unsupported scan type for ViewEntity: %T", src)
	}
	return nil
}

type NullViewEntity struct {
	ViewEntity ViewEntity `json:"view_entity"`
	Valid      bool       `json:"valid"` // Valid is true if ViewEntity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullViewEntity) Scan(value interface{}) error {
	if value == nil {
		ns.ViewEntity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ViewEntity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullViewEntity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ViewEntity), nil
}

func (e ViewEntity) Valid() bool {
	switch e {
	case ViewEntityTask,
		ViewEntityProject:
		return true
	}
	return false
}

func AllViewEntityValues() []ViewEntity {
	return []ViewEntity{
		ViewEntityTask,
		ViewEntityProject,
	}
}

type Label struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Scope       LabelScope `json:"scope"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type Member struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Name        string     `json:"name"`
	Email       *string    `json:"email"`
	AvatarColor string     `json:"avatar_color"`
	UserID      *uuid.UUID `json:"user_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      ProjectStatus `json:"status"`
	Priority    int16         `json:"priority"`
	LeadID      *uuid.UUID    `json:"lead_id"`
	StartDate   *civil.Date   `json:"start_date"`
	TargetDate  *civil.Date   `json:"target_date"`
	CreatedBy   *uuid.UUID    `json:"created_by"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedAt   *time.Time    `json:"deleted_at"`
}

type ProjectLabel struct {
	ProjectID uuid.UUID `json:"project_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

type ProjectMember struct {
	ProjectID uuid.UUID `json:"project_id"`
	MemberID  uuid.UUID `json:"member_id"`
}

type SavedView struct {
	ID          uuid.UUID       `json:"id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	EntityType  ViewEntity      `json:"entity_type"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Config      json.RawMessage `json:"config"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Task struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ProjectID   *uuid.UUID  `json:"project_id"`
	ParentID    *uuid.UUID  `json:"parent_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      TaskStatus  `json:"status"`
	Priority    int16       `json:"priority"`
	AssigneeID  *uuid.UUID  `json:"assignee_id"`
	DueDate     *civil.Date `json:"due_date"`
	CreatedBy   *uuid.UUID  `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	DeletedAt   *time.Time  `json:"deleted_at"`
}

type TaskLabel struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
}

type Workspace struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
