// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package store

import (
	"context"
	"time"

	"cloud.google.com/go/civil"
	"github.com/google/uuid"
)

const addProjectMembers = `-- name: AddProjectMembers :exec
INSERT INTO project_member (project_id, member_id)
SELECT $1, unnest($2::uuid[])
`

type AddProjectMembersParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	MemberIds []uuid.UUID `json:"member_ids"`
}

func (q *Queries) AddProjectMembers(ctx context.Context, arg AddProjectMembersParams) error {
	_, err := q.db.Exec(ctx, addProjectMembers, arg.ProjectID, arg.MemberIds)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (id,workspace_id,name,description,status,priority,lead_id,start_date,target_date,created_at,updated_at)
VALUES(
    gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,NOW(),NOW()
)
RETURNING id, workspace_id, name, description, status, priority, lead_id, start_date, target_date, created_by, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      ProjectStatus `json:"status"`
	Priority    int16         `json:"priority"`
	LeadID      *uuid.UUID    `json:"lead_id"`
	StartDate   *civil.Date   `json:"start_date"`
	TargetDate  *civil.Date   `json:"target_date"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.LeadID,
		arg.StartDate,
		arg.TargetDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.LeadID,
		&i.StartDate,
		&i.TargetDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProjectMembers = `-- name: DeleteProjectMembers :exec
DELETE FROM project_member WHERE project_id = $1
`

func (q *Queries) DeleteProjectMembers(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectMembers, projectID)
	return err
}

const detachProjectTasks = `-- name: DetachProjectTasks :exec
UPDATE task SET project_id = NULL, updated_at=NOW()
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DetachProjectTasks(ctx context.Context, projectID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, detachProjectTasks, projectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT p.id, p.workspace_id, p.name, p.description, p.status, p.priority, p.lead_id, p.start_date, p.target_date, p.created_by, p.created_at, p.updated_at, p.deleted_at, m.name AS lead_name, m.avatar_color AS lead_avatar_color,
(SELECT COUNT(*) FROM task WHERE project_id = p.id AND deleted_at IS NULL) AS task_count 
FROM project p 
LEFT JOIN member m ON p.lead_id = m.id
WHERE p.id = $1
AND p.workspace_id = $2 AND p.deleted_at IS NULL
`

type GetProjectParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetProjectRow struct {
	ID              uuid.UUID     `json:"id"`
	WorkspaceID     uuid.UUID     `json:"workspace_id"`
	Name            string        `json:"name"`
	Description     string        `json:"description"`
	Status          ProjectStatus `json:"status"`
	Priority        int16         `json:"priority"`
	LeadID          *uuid.UUID    `json:"lead_id"`
	StartDate       *civil.Date   `json:"start_date"`
	TargetDate      *civil.Date   `json:"target_date"`
	CreatedBy       *uuid.UUID    `json:"created_by"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	DeletedAt       *time.Time    `json:"deleted_at"`
	LeadName        *string       `json:"lead_name"`
	LeadAvatarColor *string       `json:"lead_avatar_color"`
	TaskCount       int64         `json:"task_count"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.WorkspaceID)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.LeadID,
		&i.StartDate,
		&i.TargetDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LeadName,
		&i.LeadAvatarColor,
		&i.TaskCount,
	)
	return i, err
}

const ifProjectExists = `-- name: IfProjectExists :one
SELECT EXISTS(SELECT 1 FROM project WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL)
`

type IfProjectExistsParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// 判断项目是否存在 用GetProject太复杂，所以单独写一个判断
func (q *Queries) IfProjectExists(ctx context.Context, arg IfProjectExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, ifProjectExists, arg.ID, arg.WorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLabelsByProjectIds = `-- name: ListLabelsByProjectIds :many
SELECT pl.project_id, l.id, l.workspace_id, l.scope, l.name, l.color, l.created_at, l.updated_at
FROM project_label pl
JOIN label l ON pl.label_id = l.id
WHERE pl.project_id = ANY($1::uuid[])
ORDER BY pl.project_id, l.created_at
`

type ListLabelsByProjectIdsRow struct {
	ProjectID   uuid.UUID  `json:"project_id"`
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Scope       LabelScope `json:"scope"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// 项目列表批量组装用：一次取回全部项目的标签，handler 内存分组避免 N+1
// 每个项目组内仍须 created_at 升序（api.md §4），故 ORDER BY 带上 l.created_at
func (q *Queries) ListLabelsByProjectIds(ctx context.Context, projectIds []uuid.UUID) ([]ListLabelsByProjectIdsRow, error) {
	rows, err := q.db.Query(ctx, listLabelsByProjectIds, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelsByProjectIdsRow
	for rows.Next() {
		var i ListLabelsByProjectIdsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.WorkspaceID,
			&i.Scope,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLabels = `-- name: ListProjectLabels :many
SELECT l.id, l.workspace_id, l.scope, l.name, l.color, l.created_at, l.updated_at
FROM project_label pl
JOIN label l ON pl.label_id = l.id
WHERE pl.project_id = $1
ORDER BY l.created_at
`

// 项目详情用：labels 按 created_at 升序（api.md §4）
func (q *Queries) ListProjectLabels(ctx context.Context, projectID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listProjectLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Scope,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMemberIdsByProjectIds = `-- name: ListProjectMemberIdsByProjectIds :many
SELECT pm.project_id, pm.member_id
FROM project_member pm
WHERE pm.project_id = ANY($1::uuid[])
ORDER BY pm.project_id
`

// P2 member 过滤求值用（P2.md §2.5）：批量取 project→member id 映射，
// 与 ListLabelsByProjectIds 同构避免 N+1；仅 member 条件存在时调用
func (q *Queries) ListProjectMemberIdsByProjectIds(ctx context.Context, projectIds []uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMemberIdsByProjectIds, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(&i.ProjectID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.id, m.workspace_id, m.name, m.email, m.avatar_color, m.user_id, m.created_at, m.updated_at 
FROM project_member pm
JOIN member m ON pm.member_id = m.id
WHERE pm.project_id = $1
ORDER BY m.name
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Email,
			&i.AvatarColor,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByWorkspace = `-- name: ListProjectsByWorkspace :many
SELECT p.id, p.workspace_id, p.name, p.description, p.status, p.priority, p.lead_id, p.start_date, p.target_date, p.created_by, p.created_at, p.updated_at, p.deleted_at,m.name AS lead_name, m.avatar_color AS lead_avatar_color,
(SELECT COUNT(*) FROM task WHERE project_id = p.id AND deleted_at IS NULL) AS task_count 
FROM project p 
LEFT JOIN member m ON p.lead_id = m.id
WHERE p.workspace_id = $1 AND p.deleted_at IS NULL
`

type ListProjectsByWorkspaceRow struct {
	ID              uuid.UUID     `json:"id"`
	WorkspaceID     uuid.UUID     `json:"workspace_id"`
	Name            string        `json:"name"`
	Description     string        `json:"description"`
	Status          ProjectStatus `json:"status"`
	Priority        int16         `json:"priority"`
	LeadID          *uuid.UUID    `json:"lead_id"`
	StartDate       *civil.Date   `json:"start_date"`
	TargetDate      *civil.Date   `json:"target_date"`
	CreatedBy       *uuid.UUID    `json:"created_by"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	DeletedAt       *time.Time    `json:"deleted_at"`
	LeadName        *string       `json:"lead_name"`
	LeadAvatarColor *string       `json:"lead_avatar_color"`
	TaskCount       int64         `json:"task_count"`
}

func (q *Queries) ListProjectsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListProjectsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByWorkspaceRow
	for rows.Next() {
		var i ListProjectsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.LeadID,
			&i.StartDate,
			&i.TargetDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LeadName,
			&i.LeadAvatarColor,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE project SET deleted_at=NOW() WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// 必须带 deleted_at IS NULL：否则重复删除已软删项目仍影响 1 行 → 返 204，
// 而 api.md §7 约定“目标不存在（含已软删、跨工作区）→ 404”（锚点条件同 SoftDeleteTaskSubtree）
func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE project SET name = $1, description = $2, status = $3, priority = $4, lead_id = $5, start_date = $6, target_date = $7, updated_at=NOW() 
WHERE id = $8 AND workspace_id = $9 AND deleted_at IS NULL
RETURNING id, workspace_id, name, description, status, priority, lead_id, start_date, target_date, created_by, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      ProjectStatus `json:"status"`
	Priority    int16         `json:"priority"`
	LeadID      *uuid.UUID    `json:"lead_id"`
	StartDate   *civil.Date   `json:"start_date"`
	TargetDate  *civil.Date   `json:"target_date"`
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.LeadID,
		arg.StartDate,
		arg.TargetDate,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.LeadID,
		&i.StartDate,
		&i.TargetDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
