// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package store

import (
	"context"
	"time"

	"cloud.google.com/go/civil"
	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO task (id,workspace_id,project_id,parent_id,title,description,status,priority,assignee_id,due_date,created_at,updated_at)
VALUES(
    gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,$9,NOW(),NOW()
)
RETURNING id, workspace_id, project_id, parent_id, title, description, status, priority, assignee_id, due_date, created_by, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ProjectID   *uuid.UUID  `json:"project_id"`
	ParentID    *uuid.UUID  `json:"parent_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      TaskStatus  `json:"status"`
	Priority    int16       `json:"priority"`
	AssigneeID  *uuid.UUID  `json:"assignee_id"`
	DueDate     *civil.Date `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ParentID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
WITH RECURSIVE d AS (
    SELECT c.parent_id AS root_id, c.id, c.status
    FROM task c
    WHERE c.parent_id IS NOT NULL AND c.deleted_at IS NULL
    UNION ALL
    SELECT d.root_id, c.id, c.status
    FROM task c JOIN d ON c.parent_id = d.id
    WHERE c.deleted_at IS NULL
), ps AS (
    SELECT root_id, COUNT(*) FILTER (WHERE status = 'done') AS done_count, COUNT(*) AS total_count
    FROM d GROUP BY root_id
)
SELECT t.id, t.workspace_id, t.project_id, t.parent_id, t.title, t.description, t.status, t.priority, t.assignee_id, t.due_date, t.created_by, t.created_at, t.updated_at, t.deleted_at, p.name AS project_name, m.name AS assignee_name, m.avatar_color AS assignee_avatar_color,
pt.title AS parent_title, pt.status AS parent_status,
ps.done_count AS parent_sub_done, ps.total_count AS parent_sub_total
FROM task t
LEFT JOIN project p ON t.project_id = p.id
LEFT JOIN member m ON t.assignee_id = m.id
LEFT JOIN task pt ON t.parent_id = pt.id
LEFT JOIN ps ON ps.root_id = t.parent_id
WHERE t.id = $1 
AND t.workspace_id = $2 AND t.deleted_at IS NULL
`

type GetTaskParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetTaskRow struct {
	ID                  uuid.UUID   `json:"id"`
	WorkspaceID         uuid.UUID   `json:"workspace_id"`
	ProjectID           *uuid.UUID  `json:"project_id"`
	ParentID            *uuid.UUID  `json:"parent_id"`
	Title               string      `json:"title"`
	Description         string      `json:"description"`
	Status              TaskStatus  `json:"status"`
	Priority            int16       `json:"priority"`
	AssigneeID          *uuid.UUID  `json:"assignee_id"`
	DueDate             *civil.Date `json:"due_date"`
	CreatedBy           *uuid.UUID  `json:"created_by"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	DeletedAt           *time.Time  `json:"deleted_at"`
	ProjectName         *string     `json:"project_name"`
	AssigneeName        *string     `json:"assignee_name"`
	AssigneeAvatarColor *string     `json:"assignee_avatar_color"`
	ParentTitle         *string     `json:"parent_title"`
	ParentStatus        *TaskStatus `json:"parent_status"`
	ParentSubDone       *int64      `json:"parent_sub_done"`
	ParentSubTotal      *int64      `json:"parent_sub_total"`
}

// 父任务引用（status/title）+ 父任务后代完成统计（口径同 Sub-issues 徽标 api.md §4），
// 供子任务详情页 "Sub-issue of" 行渲染（对齐 Linear）；无父时父列为 NULL、统计为 NULL。
// 统计用顶层递归 CTE 算全量 (root → 后代) 闭包再聚合（sqlc 解析器不支持 LATERAL 内嵌递归）
func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.WorkspaceID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectName,
		&i.AssigneeName,
		&i.AssigneeAvatarColor,
		&i.ParentTitle,
		&i.ParentStatus,
		&i.ParentSubDone,
		&i.ParentSubTotal,
	)
	return i, err
}

const getTaskSubtree = `-- name: GetTaskSubtree :many
WITH RECURSIVE subtree AS (
    SELECT t.id, t.parent_id, 0 AS depth
    FROM task t
    WHERE t.id = $1 AND t.workspace_id = $2 AND t.deleted_at IS NULL
    UNION ALL
    SELECT t.id, t.parent_id, s.depth + 1
    FROM task t
    JOIN subtree s ON t.parent_id = s.id
    WHERE t.workspace_id = $2 AND t.deleted_at IS NULL
)
SELECT t.id, t.parent_id, s.depth, t.title, t.status, t.priority,
       t.due_date, t.created_at,
       t.project_id, p.name AS project_name,
       t.assignee_id, m.name AS assignee_name, m.avatar_color AS assignee_avatar_color
FROM subtree s
JOIN task t ON t.id = s.id
LEFT JOIN project p ON t.project_id = p.id
LEFT JOIN member m ON t.assignee_id = m.id
WHERE s.depth > 0
ORDER BY s.depth, t.created_at
`

type GetTaskSubtreeParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetTaskSubtreeRow struct {
	ID                  uuid.UUID   `json:"id"`
	ParentID            *uuid.UUID  `json:"parent_id"`
	Depth               int32       `json:"depth"`
	Title               string      `json:"title"`
	Status              TaskStatus  `json:"status"`
	Priority            int16       `json:"priority"`
	DueDate             *civil.Date `json:"due_date"`
	CreatedAt           time.Time   `json:"created_at"`
	ProjectID           *uuid.UUID  `json:"project_id"`
	ProjectName         *string     `json:"project_name"`
	AssigneeID          *uuid.UUID  `json:"assignee_id"`
	AssigneeName        *string     `json:"assignee_name"`
	AssigneeAvatarColor *string     `json:"assignee_avatar_color"`
}

// get s.due_date lead to **time.Time
func (q *Queries) GetTaskSubtree(ctx context.Context, arg GetTaskSubtreeParams) ([]GetTaskSubtreeRow, error) {
	rows, err := q.db.Query(ctx, getTaskSubtree, arg.ID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskSubtreeRow
	for rows.Next() {
		var i GetTaskSubtreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Depth,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.ProjectID,
			&i.ProjectName,
			&i.AssigneeID,
			&i.AssigneeName,
			&i.AssigneeAvatarColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ifTaskExist = `-- name: IfTaskExist :one
SELECT EXISTS (SELECT 1 FROM task WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL)
`

type IfTaskExistParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// 判断任务是否存在 用GetTask太复杂，所以单独写一个判断
func (q *Queries) IfTaskExist(ctx context.Context, arg IfTaskExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, ifTaskExist, arg.ID, arg.WorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT t.id, t.workspace_id, t.project_id, t.parent_id, t.title, t.description, t.status, t.priority, t.assignee_id, t.due_date, t.created_by, t.created_at, t.updated_at, t.deleted_at, p.name AS project_name, m.name AS assignee_name, m.avatar_color AS assignee_avatar_color, pt.title AS parent_title
FROM task t 
LEFT JOIN project p ON t.project_id = p.id
LEFT JOIN member m ON t.assignee_id = m.id
LEFT JOIN task pt ON t.parent_id = pt.id
WHERE t.project_id = $1 AND t.workspace_id = $2 AND t.deleted_at IS NULL
ORDER BY CASE t.status WHEN 'backlog' THEN 1 WHEN 'todo' THEN 2 WHEN 'in_progress' THEN 3 WHEN 'done' THEN 4 ELSE 5 END, t.created_at
`

type ListTasksByProjectParams struct {
	ProjectID   *uuid.UUID `json:"project_id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
}

type ListTasksByProjectRow struct {
	ID                  uuid.UUID   `json:"id"`
	WorkspaceID         uuid.UUID   `json:"workspace_id"`
	ProjectID           *uuid.UUID  `json:"project_id"`
	ParentID            *uuid.UUID  `json:"parent_id"`
	Title               string      `json:"title"`
	Description         string      `json:"description"`
	Status              TaskStatus  `json:"status"`
	Priority            int16       `json:"priority"`
	AssigneeID          *uuid.UUID  `json:"assignee_id"`
	DueDate             *civil.Date `json:"due_date"`
	CreatedBy           *uuid.UUID  `json:"created_by"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	DeletedAt           *time.Time  `json:"deleted_at"`
	ProjectName         *string     `json:"project_name"`
	AssigneeName        *string     `json:"assignee_name"`
	AssigneeAvatarColor *string     `json:"assignee_avatar_color"`
	ParentTitle         *string     `json:"parent_title"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]ListTasksByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, arg.ProjectID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByProjectRow
	for rows.Next() {
		var i ListTasksByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectName,
			&i.AssigneeName,
			&i.AssigneeAvatarColor,
			&i.ParentTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByWorkspace = `-- name: ListTasksByWorkspace :many
SELECT t.id, t.workspace_id, t.project_id, t.parent_id, t.title, t.description, t.status, t.priority, t.assignee_id, t.due_date, t.created_by, t.created_at, t.updated_at, t.deleted_at, p.name AS project_name, m.name AS assignee_name, m.avatar_color AS assignee_avatar_color, pt.title AS parent_title
FROM task t
LEFT JOIN project p ON t.project_id = p.id
LEFT JOIN member m ON t.assignee_id = m.id
LEFT JOIN task pt ON t.parent_id = pt.id
WHERE t.workspace_id = $1 AND t.deleted_at IS NULL
AND (cardinality($2 ::task_status[]) = 0 OR t.status = ANY($2 ::task_status[]))
ORDER BY CASE t.status WHEN 'backlog' THEN 1 WHEN 'todo' THEN 2 WHEN 'in_progress' THEN 3 WHEN 'done' THEN 4 ELSE 5 END, t.created_at
`

type ListTasksByWorkspaceParams struct {
	WorkspaceID uuid.UUID    `json:"workspace_id"`
	Statuses    []TaskStatus `json:"statuses"`
}

type ListTasksByWorkspaceRow struct {
	ID                  uuid.UUID   `json:"id"`
	WorkspaceID         uuid.UUID   `json:"workspace_id"`
	ProjectID           *uuid.UUID  `json:"project_id"`
	ParentID            *uuid.UUID  `json:"parent_id"`
	Title               string      `json:"title"`
	Description         string      `json:"description"`
	Status              TaskStatus  `json:"status"`
	Priority            int16       `json:"priority"`
	AssigneeID          *uuid.UUID  `json:"assignee_id"`
	DueDate             *civil.Date `json:"due_date"`
	CreatedBy           *uuid.UUID  `json:"created_by"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	DeletedAt           *time.Time  `json:"deleted_at"`
	ProjectName         *string     `json:"project_name"`
	AssigneeName        *string     `json:"assignee_name"`
	AssigneeAvatarColor *string     `json:"assignee_avatar_color"`
	ParentTitle         *string     `json:"parent_title"`
}

func (q *Queries) ListTasksByWorkspace(ctx context.Context, arg ListTasksByWorkspaceParams) ([]ListTasksByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listTasksByWorkspace, arg.WorkspaceID, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByWorkspaceRow
	for rows.Next() {
		var i ListTasksByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectName,
			&i.AssigneeName,
			&i.AssigneeAvatarColor,
			&i.ParentTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTaskSubtree = `-- name: SoftDeleteTaskSubtree :execrows


WITH RECURSIVE subtree AS (
    SELECT t.id FROM task t WHERE t.id = $1 AND t.workspace_id = $2 AND t.deleted_at IS NULL
    UNION ALL
    SELECT t.id FROM task t JOIN subtree s ON t.parent_id = s.id WHERE t.workspace_id = $2 AND t.deleted_at IS NULL
)
UPDATE task SET deleted_at = NOW(), updated_at = NOW()
WHERE id IN (SELECT id FROM subtree)
`

type SoftDeleteTaskSubtreeParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// DeleteTask can be done with SoftDeleteTaskSubtree
// UPDATE task SET deleted_at=NOW() WHERE id = $1;
func (q *Queries) SoftDeleteTaskSubtree(ctx context.Context, arg SoftDeleteTaskSubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTaskSubtree, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const syncSubtreeProject = `-- name: SyncSubtreeProject :exec
WITH RECURSIVE subtree AS (
    SELECT t.id FROM task t WHERE t.parent_id = $1 AND t.deleted_at IS NULL
    UNION ALL
    SELECT t.id FROM task t JOIN subtree s ON t.parent_id = s.id WHERE t.deleted_at IS NULL
)
UPDATE task SET project_id = $2, updated_at = NOW()
WHERE id IN (SELECT id FROM subtree)
`

type SyncSubtreeProjectParams struct {
	ParentID  *uuid.UUID `json:"parent_id"`
	ProjectID *uuid.UUID `json:"project_id"`
}

func (q *Queries) SyncSubtreeProject(ctx context.Context, arg SyncSubtreeProjectParams) error {
	_, err := q.db.Exec(ctx, syncSubtreeProject, arg.ParentID, arg.ProjectID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE task SET project_id = $1, title = $2, description = $3, status = $4, priority = $5, assignee_id = $6, due_date = $7, updated_at=NOW()
WHERE id = $8 AND workspace_id = $9 AND deleted_at IS NULL
RETURNING id, workspace_id, project_id, parent_id, title, description, status, priority, assignee_id, due_date, created_by, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ProjectID   *uuid.UUID  `json:"project_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      TaskStatus  `json:"status"`
	Priority    int16       `json:"priority"`
	AssigneeID  *uuid.UUID  `json:"assignee_id"`
	DueDate     *civil.Date `json:"due_date"`
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
