// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createView = `-- name: CreateView :one
INSERT INTO saved_view (workspace_id, entity_type, surface, project_id, name, description, config)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, entity_type, name, description, config, created_at, updated_at, surface, project_id
`

type CreateViewParams struct {
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	EntityType  ViewEntity      `json:"entity_type"`
	Surface     ViewSurface     `json:"surface"`
	ProjectID   *uuid.UUID      `json:"project_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Config      json.RawMessage `json:"config"`
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (SavedView, error) {
	row := q.db.QueryRow(ctx, createView,
		arg.WorkspaceID,
		arg.EntityType,
		arg.Surface,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Config,
	)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Surface,
		&i.ProjectID,
	)
	return i, err
}

const deleteView = `-- name: DeleteView :exec
DELETE FROM saved_view
WHERE id = $1 AND workspace_id = $2
`

type DeleteViewParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteView(ctx context.Context, arg DeleteViewParams) error {
	_, err := q.db.Exec(ctx, deleteView, arg.ID, arg.WorkspaceID)
	return err
}

const getView = `-- name: GetView :one
SELECT id, workspace_id, entity_type, name, description, config, created_at, updated_at, surface, project_id FROM saved_view
WHERE id = $1 AND workspace_id = $2
`

type GetViewParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetView(ctx context.Context, arg GetViewParams) (SavedView, error) {
	row := q.db.QueryRow(ctx, getView, arg.ID, arg.WorkspaceID)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Surface,
		&i.ProjectID,
	)
	return i, err
}

const listViewsByProject = `-- name: ListViewsByProject :many
SELECT id, workspace_id, entity_type, name, description, config, created_at, updated_at, surface, project_id FROM saved_view
WHERE workspace_id = $1 AND surface = 'project_issues' AND project_id = $2
ORDER BY created_at
`

type ListViewsByProjectParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
}

func (q *Queries) ListViewsByProject(ctx context.Context, arg ListViewsByProjectParams) ([]SavedView, error) {
	rows, err := q.db.Query(ctx, listViewsByProject, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedView
	for rows.Next() {
		var i SavedView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Surface,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewsBySurface = `-- name: ListViewsBySurface :many
SELECT id, workspace_id, entity_type, name, description, config, created_at, updated_at, surface, project_id FROM saved_view
WHERE workspace_id = $1 AND surface = $2
ORDER BY created_at
`

type ListViewsBySurfaceParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Surface     ViewSurface `json:"surface"`
}

func (q *Queries) ListViewsBySurface(ctx context.Context, arg ListViewsBySurfaceParams) ([]SavedView, error) {
	rows, err := q.db.Query(ctx, listViewsBySurface, arg.WorkspaceID, arg.Surface)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedView
	for rows.Next() {
		var i SavedView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Surface,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewsBySurfaceAndEntityType = `-- name: ListViewsBySurfaceAndEntityType :many
SELECT id, workspace_id, entity_type, name, description, config, created_at, updated_at, surface, project_id FROM saved_view
WHERE workspace_id = $1 AND surface = $2 AND entity_type = $3
ORDER BY created_at
`

type ListViewsBySurfaceAndEntityTypeParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Surface     ViewSurface `json:"surface"`
	EntityType  ViewEntity  `json:"entity_type"`
}

func (q *Queries) ListViewsBySurfaceAndEntityType(ctx context.Context, arg ListViewsBySurfaceAndEntityTypeParams) ([]SavedView, error) {
	rows, err := q.db.Query(ctx, listViewsBySurfaceAndEntityType, arg.WorkspaceID, arg.Surface, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedView
	for rows.Next() {
		var i SavedView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EntityType,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Surface,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateView = `-- name: UpdateView :one
UPDATE saved_view
SET name = $3, description = $4, config = $5, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, entity_type, name, description, config, created_at, updated_at, surface, project_id
`

type UpdateViewParams struct {
	ID          uuid.UUID       `json:"id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Config      json.RawMessage `json:"config"`
}

// 读-改-写：handler 先 GetView 取基准行合并 presence 字段后全量写回（单条写不开事务，api.md §2.4）
func (q *Queries) UpdateView(ctx context.Context, arg UpdateViewParams) (SavedView, error) {
	row := q.db.QueryRow(ctx, updateView,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Config,
	)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EntityType,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Surface,
		&i.ProjectID,
	)
	return i, err
}
